version: "3"
services:
  next-app:
    image: jodishwaran/ganesh-blog:next-app
    restart: always
  nginx:
    depends_on:
      - next-app
    image: jodishwaran/ganesh-blog:nginx
    volumes:
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email jodishwaran@gmail.com --agree-tos --no-eff-email --force-renewal -d jodishwaran.dev  -d www.jodishwaran.dev
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ganesh/docker-blog/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ganesh/docker-blog/dhparam/
      o: bind
# https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose
